
# This template file will have its environment variables expanded
# and the .template extension removed by the bash-template Wercker step.
# See wercker.yml.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstclass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: firstclass
  template:
    metadata:
      labels:
        app: firstclass
    spec:
      containers:
      - name: firstclass
        image: $DOCKER_REPO:$WERCKER_GIT_COMMIT
        ports:
        - name: firstclass
          containerPort: 5000
          protocol: TCP
      imagePullSecrets:
      - name:  $OKE_IMAGESECRET
#test
